---
apiVersion: v1
kind: Secret
metadata:
  name: dod-race-app-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/fmenesesg/dod-race-app-gitops
